add check

diff --git a/.github/workflows/flow.yml b/.github/workflows/flow.yml
--- a/.github/workflows/flow.yml
+++ b/.github/workflows/flow.yml
@@ -32,6 +32,17 @@ on:
 
 jobs:
   # TODO: add check for release branches only
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch name
+        run: |
+          branch_name=$(git branch --show-current)
+          if [[ $branch_name != release/R* ]]; then
+            echo "Error: Branch name must start with 'release/R'."
+            exit 1
+          fi
+
   echo_all:
     name: echo all
     runs-on: ubuntu-latest
